# SPDX-FileCopyrightText: 2026 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
  "extern/cmocka/**/"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Jason Pena <jasonpena@awkless.com>"
SPDX-License-Identifier = "Apache-2.0"
