# SPDX-FileCopyrightText: 2026 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "docs/**/"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jason Pena <jasonpena@awkless.com>"
SPDX-License-Identifier = "MIT"
